CREATE TABLE [dbo].[PlayList]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Created] DATETIME NULL DEFAULT CURRENT_TIMESTAMP, 
    [UserId] UNIQUEIDENTIFIER NULL, 
    [Name] VARCHAR(250) NULL, 
    [Description] VARCHAR(250) NULL, 
    [Image] VARCHAR(MAX) NULL
)
