CREATE TABLE [dbo].[User]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Email] VARCHAR(MAX) NULL, 
    [Created] DATETIME NULL DEFAULT CURRENT_TIMESTAMP, 
    [Active] BIT NULL DEFAULT 1, 
    [AspNetUserId] VARCHAR(MAX) NULL
)
